import { Button, Center } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center minH={"100vh"}>
          <Link href={"/new-lead"} passHref>
            <Button colorScheme={"teal"}>Create new lead</Button>
          </Link>
        </Center>
      </main>
    </div>
  );
}
